spring.application.name=ms_usuario

server.port=8083

spring.datasource.url=jdbc:mysql://mysql-35e6df79-varas5011-9353.c.aivencloud.com:12467/usuarios_login?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_M_zCh8cBC-wYBdFCOuF
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect